// AUTO-GENERATED by scripts/gen-next.mjs — do not edit.
// Bundle entry for the 'detail' native page, next-style frontend.
import { mount } from '../../mpa/mount.js';
import { routeTree } from '../../routeTree.next.gen.js';
import { manifest } from '../../routes-next.manifest.js';

mount({ pageId: 'detail', routeTree, manifest });
