// Copyright (c) 2026 TikTok Pte. Ltd.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.
import { createRouter } from '@tanstack/react-router';
import {
  createMpaHistory,
  createManifestPageResolver,
  defaultHrefForPage,
} from 'sparkling-history';
import { createSparklingHost } from 'sparkling-history/sparkling';
import * as navigation from 'sparkling-navigation';
// Route tree generated by @tanstack/router-generator (official file-based
// generator); manifest generated by scripts/gen-mpa.mjs (our MPA extension).
// Both derive from src/routes/*.
import { routeTree } from '../routeTree.gen.js';
import { manifest } from '../routes.manifest.js';
// Extensionless on purpose: resolves to web-nav/setup.web.ts in the website
// (go-web) build via the `.web.ts` extension preference, and to the native
// no-op stub (setup.ts) otherwise. See below.
import { setupWebNav } from '../web-nav/setup';

/**
 * Read this page's launch query params. On a real sparkling page these are
 * injected by the native container (or, on the web harness, by the shell) as
 * `lynx.__globalProps.queryItems`.
 */
function readQueryItems(): Record<string, string> {
  // `lynx` is a bare ambient global in the Lynx runtime (not necessarily on
  // globalThis), so reference it directly with a guarded fallback.
  const g = globalThis as {
    lynx?: { __globalProps?: { queryItems?: Record<string, string> } };
  };
  const lynxGlobal =
    typeof lynx !== 'undefined'
      ? (lynx as { __globalProps?: { queryItems?: Record<string, string> } })
      : g.lynx;
  return lynxGlobal?.__globalProps?.queryItems ?? {};
}

function LynxErrorComponent({ error }: { error: Error }) {
  console.error('[mpa] route error:', error.message, error.stack);
  return (
    <view style={{ padding: '48px 20px' }}>
      <text style={{ color: '#f87171', fontSize: '15px' }}>{`Error: ${error.message}`}</text>
    </view>
  );
}

/**
 * Build a TanStack Router wired to sparkling-navigation through the history
 * shim. Cross-page navigations become native page opens; in-page navigations
 * stay within this bundle.
 */
export function createMpaRouter(opts?: { pageId?: string }) {
  const host = createSparklingHost({
    navigation: navigation as never,
    getQueryItems: readQueryItems,
    // External deep links open this bundle without `__mpa_href`; render this
    // page's own default route, not the app root.
    defaultHref: opts?.pageId ? defaultHrefForPage(manifest, opts.pageId) : '/',
  });

  // In the go-web `<Go>` preview, the sparkling web bridge routes a cross-page
  // `router.open` back into THIS card (a card renders one bundle and can't swap
  // to another native page). `setupWebNav` (web build only) does that in-page
  // re-entry; this flag makes the re-entrant navigation bypass the manifest so
  // it does not dispatch to the host again (which would loop). On native the
  // stub is a no-op and the flag stays false.
  let inCardNav = false;
  const resolvePage = createManifestPageResolver(manifest);

  const history = createMpaHistory({
    host,
    resolvePage: (href, ctx) => (inCardNav ? null : resolvePage(href, ctx)),
    onHostError: (e) => console.error('[mpa] host error:', e),
  });

  const router = createRouter({
    routeTree,
    history: history as never,
    isServer: false,
    // router-core reads a bare `window.origin` when isServer is false; a
    // native Lynx runtime has no `window`, so pin the origin explicitly.
    origin: 'http://sparkling.local',
    defaultErrorComponent: LynxErrorComponent as never,
    defaultNotFoundComponent: (() => (
      <view style={{ padding: '48px 20px' }}>
        <text style={{ color: '#f87171' }}>Not found</text>
      </view>
    )) as never,
  });

  // Web build: register the sparkling `router.open`/`close` web methods and
  // point their host at this card (in-page). Native build: no-op stub, so the
  // native bridge is never hijacked.
  setupWebNav({
    history,
    onEnterInPage: () => {
      inCardNav = true;
    },
    onExitInPage: () => {
      inCardNav = false;
    },
  });

  return router;
}
