// AUTO-GENERATED by scripts/gen-mpa.mjs — do not edit.
// Pruned route tree for the 'home' page: only this page's routes
// carry components/options; every other route is a path-only stub for
// href building. The full tree (routeTree.gen.ts) stays the type-level
// source of truth.
/* eslint-disable @typescript-eslint/no-explicit-any */
import { createRootRoute, createRoute } from '@tanstack/react-router';
import { Route as rootRouteImport } from '../../routes/__root.js';
import { Route as R_index } from '../../routes/index.js';
import { Route as R_profile } from '../../routes/profile.js';

// Fresh root cloned from the app root's options: pruned trees must not
// mutate shared file-route singletons (the full tree links them too).
const root = createRootRoute((rootRouteImport as any).options);

const R_index_route = createRoute({
  ...(R_index as any).options,
  path: '/',
  getParentRoute: () => root,
});
const R_profile_route = createRoute({
  ...(R_profile as any).options,
  path: '/profile',
  getParentRoute: () => root,
});
// '/detail/$id' lives in page 'detail' — path-only stub.
const stub_0 = createRoute({ path: '/detail/$id', getParentRoute: () => root });
// '/settings' lives in page 'settings' — path-only stub.
const stub_1 = createRoute({ path: '/settings', getParentRoute: () => root });

export const routeTree = root.addChildren([R_index_route, R_profile_route, stub_0, stub_1]);
