// AUTO-GENERATED by scripts/gen-next.mjs — do not edit.
export const nextPageEntries = {
  "detail": "./src/pages-next.gen/detail/index.tsx",
  "home": "./src/pages-next.gen/home/index.tsx",
  "settings": "./src/pages-next.gen/settings/index.tsx"
};
