// AUTO-GENERATED by scripts/gen-mpa.mjs — do not edit.
export const pageEntries = {
  "detail": "./src/pages.gen/detail/index.tsx",
  "home": "./src/pages.gen/home/index.tsx",
  "settings": "./src/pages.gen/settings/index.tsx"
};
