// AUTO-GENERATED by scripts/gen-mpa.mjs — do not edit.
// Route -> native-page (bundle) mapping, derived from src/routes/*.
import type { RouteManifest } from 'sparkling-router';

export const manifest: RouteManifest = {
  "version": "prototype-1",
  "scheme": {
    "base": "hybrid://lynxview_page"
  },
  "containers": [
    {
      "id": "detail",
      "bundle": "detail.lynx.bundle",
      "presentation": "push",
      "routes": [
        {
          "path": "/detail/$id"
        }
      ],
      "containerOptions": {
        "title": "Detail"
      }
    },
    {
      "id": "home",
      "bundle": "home.lynx.bundle",
      "presentation": "push",
      "routes": [
        {
          "path": "/"
        },
        {
          "path": "/profile"
        }
      ]
    },
    {
      "id": "settings",
      "bundle": "settings.lynx.bundle",
      "presentation": "push",
      "routes": [
        {
          "path": "/settings"
        }
      ],
      "containerOptions": {
        "title": "Settings"
      }
    }
  ]
};
