// AUTO-GENERATED by scripts/gen-next.mjs — do not edit.
// Route -> native-page (bundle) mapping, schema v1.
import type { PageManifest } from 'sparkling-history';

export const manifest: PageManifest = {
  "version": 1,
  "scheme": {
    "base": "hybrid://lynxview_page"
  },
  "pages": [
    {
      "id": "detail",
      "paths": [
        "/detail"
      ],
      "containerParams": {
        "title": "Detail"
      },
      "defaultHref": "/detail"
    },
    {
      "id": "home",
      "paths": [
        "/",
        "/profile"
      ],
      "defaultHref": "/"
    },
    {
      "id": "settings",
      "paths": [
        "/settings"
      ],
      "presentation": "modal",
      "containerParams": {
        "title": "Settings"
      },
      "defaultHref": "/settings"
    }
  ]
};
