// AUTO-GENERATED by scripts/gen-mpa.mjs — do not edit.
// Route -> native-page (bundle) mapping, derived from src/routes/*.
import type { PageManifest } from 'sparkling-history';

export const manifest: PageManifest = {
  "pages": [
    {
      "id": "detail",
      "paths": [
        "/detail"
      ],
      "containerParams": {
        "title": "Detail"
      },
      "defaultHref": "/detail"
    },
    {
      "id": "home",
      "paths": [
        "/",
        "/profile"
      ],
      "defaultHref": "/"
    },
    {
      "id": "settings",
      "paths": [
        "/settings"
      ],
      "containerParams": {
        "title": "Settings"
      },
      "defaultHref": "/settings"
    }
  ]
};
