/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes-next.gen/__root';
import { Route as SettingsRouteImport } from './routes-next.gen/settings';
import { Route as ProfileRouteImport } from './routes-next.gen/profile';
import { Route as IndexRouteImport } from './routes-next.gen/index';
import { Route as DetailIdRouteImport } from './routes-next.gen/detail.$id';

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any);
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const DetailIdRoute = DetailIdRouteImport.update({
  id: '/detail/$id',
  path: '/detail/$id',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/profile': typeof ProfileRoute;
  '/settings': typeof SettingsRoute;
  '/detail/$id': typeof DetailIdRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/profile': typeof ProfileRoute;
  '/settings': typeof SettingsRoute;
  '/detail/$id': typeof DetailIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/profile': typeof ProfileRoute;
  '/settings': typeof SettingsRoute;
  '/detail/$id': typeof DetailIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/profile' | '/settings' | '/detail/$id';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/profile' | '/settings' | '/detail/$id';
  id: '__root__' | '/' | '/profile' | '/settings' | '/detail/$id';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ProfileRoute: typeof ProfileRoute;
  SettingsRoute: typeof SettingsRoute;
  DetailIdRoute: typeof DetailIdRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/profile': {
      id: '/profile';
      path: '/profile';
      fullPath: '/profile';
      preLoaderRoute: typeof ProfileRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/detail/$id': {
      id: '/detail/$id';
      path: '/detail/$id';
      fullPath: '/detail/$id';
      preLoaderRoute: typeof DetailIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  DetailIdRoute: DetailIdRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
