// AUTO-GENERATED by scripts/gen-next.mjs — do not edit.
import { createRootRoute, Outlet } from '@tanstack/react-router';
import RootLayout from '../app/layout.js';

export const Route = createRootRoute({
  component: () => (
    <RootLayout>
      <Outlet />
    </RootLayout>
  ),
});
