// AUTO-GENERATED by scripts/gen-next.mjs — do not edit.
import { createFileRoute } from '@tanstack/react-router';
import Page, { routeOptions } from '../app/detail/[id]/page.js';

// Page boundary translated from `export const container` in the app file.
export const page = {"id":"detail","containerParams":{"title":"Detail"}};

export const Route = createFileRoute('/detail/$id')({
  ...routeOptions,
  component: Page,
});
