// AUTO-GENERATED by scripts/gen-next.mjs — do not edit.
import { createFileRoute } from '@tanstack/react-router';
import Page from '../app/page.js';

// Page boundary translated from `export const container` in the app file.
export const page = {"id":"home","root":true};

export const Route = createFileRoute('/')({
  component: Page,
});
