// AUTO-GENERATED by scripts/gen-next.mjs — do not edit.
import { createFileRoute } from '@tanstack/react-router';
import Page from '../app/profile/page.js';

export const Route = createFileRoute('/profile')({
  component: Page,
});
