// AUTO-GENERATED by scripts/gen-next.mjs — do not edit.
import { createFileRoute } from '@tanstack/react-router';
import Page from '../app/settings/page.js';

// Page boundary translated from `export const container` in the app file.
export const page = {"id":"settings","containerParams":{"title":"Settings"}};

export const Route = createFileRoute('/settings')({
  component: Page,
});
