// Copyright (c) 2026 TikTok Pte. Ltd.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.
//
// MPA codegen — the piece TanStack Router's own generator does not provide.
//
// TanStack's @tanstack/router-generator turns the file convention into a route
// tree (routeTree.gen.ts), assuming one router / one bundle. An MPA needs two
// more artifacts derived from the SAME route files:
//
//   1. src/routes.manifest.ts   — the route -> native-page (bundle) mapping
//   2. src/pages.gen/<id>/index.tsx — one bundle entry per native page
//
// Page boundaries are declared with an `export const page = { id, ... }` in a
// route file (our extension to the convention). Routes without a `page` export
// belong to the root page (the one whose `page` has `root: true`).
import { readdirSync, readFileSync, writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { join, resolve } from 'node:path';

const ROOT = resolve(process.cwd());
const ROUTES_DIR = join(ROOT, 'src', 'routes');
const MANIFEST_OUT = join(ROOT, 'src', 'routes.manifest.ts');
const ENTRIES_DIR = join(ROOT, 'src', 'pages.gen');

/** Derive a route path from a TanStack file name (fallback if no explicit arg). */
function pathFromFileName(file) {
  let name = file.replace(/\.(tsx?|jsx?)$/, '');
  if (name === 'index') return '/';
  // `detail.$id` -> `/detail/$id`, `a.b` -> `/a/b`
  return '/' + name.split('.').join('/');
}

/** Extract the createFileRoute('...') path argument, if present. */
function extractRoutePath(src, file) {
  const m = src.match(/createFileRoute\(\s*['"]([^'"]+)['"]\s*\)/);
  return m ? m[1] : pathFromFileName(file);
}

/** Extract and evaluate the `export const page = { ... }` object literal. */
function extractPage(src) {
  const idx = src.search(/export\s+const\s+page\s*=\s*\{/);
  if (idx === -1) return undefined;
  const braceStart = src.indexOf('{', idx);
  // Brace-match to find the end of the object literal.
  let depth = 0;
  let end = -1;
  for (let i = braceStart; i < src.length; i++) {
    const c = src[i];
    if (c === '{') depth++;
    else if (c === '}') {
      depth--;
      if (depth === 0) {
        end = i;
        break;
      }
    }
  }
  if (end === -1) return undefined;
  const objText = src.slice(braceStart, end + 1);
  // Build-time eval of a literal from our own trusted source file.
  // eslint-disable-next-line no-new-func
  return Function(`"use strict"; return (${objText});`)();
}

/** The static path prefix a page owns (up to the first param segment). */
function staticPrefix(routePath) {
  const segs = routePath.split('/');
  const out = [];
  for (const seg of segs) {
    if (seg.startsWith('$') || seg === '') {
      if (seg === '' && out.length === 0) out.push(''); // keep leading '/'
      if (seg.startsWith('$')) break;
      continue;
    }
    out.push(seg);
  }
  const prefix = out.join('/') || '/';
  return prefix === '' ? '/' : prefix;
}

function main() {
  const files = readdirSync(ROUTES_DIR).filter(
    (f) => /\.(tsx?|jsx?)$/.test(f) && !f.startsWith('__'),
  );

  const routes = files.map((file) => {
    const src = readFileSync(join(ROUTES_DIR, file), 'utf8');
    return { file, path: extractRoutePath(src, file), page: extractPage(src) };
  });

  const rootPage = routes.find((r) => r.page?.root)?.page;
  if (!rootPage) {
    throw new Error('No root page found: exactly one route must export `page` with `root: true`.');
  }

  // Group route path-prefixes by page id.
  /** @type {Map<string, { id: string; paths: Set<string>; containerParams?: Record<string,string> }>} */
  const byId = new Map();
  const ensure = (id, containerParams) => {
    if (!byId.has(id)) byId.set(id, { id, paths: new Set(), containerParams });
    else if (containerParams && !byId.get(id).containerParams) byId.get(id).containerParams = containerParams;
    return byId.get(id);
  };

  for (const r of routes) {
    const pageId = r.page?.id ?? rootPage.id; // unmarked routes -> root page
    const containerParams = r.page?.containerParams;
    ensure(pageId, containerParams).paths.add(staticPrefix(r.path));
  }

  const pages = [...byId.values()].map((p) => ({
    id: p.id,
    paths: [...p.paths].sort(),
    ...(p.containerParams ? { containerParams: p.containerParams } : {}),
  }));

  // 1. Write the manifest module.
  const manifestBody =
    `// AUTO-GENERATED by scripts/gen-mpa.mjs — do not edit.\n` +
    `// Route -> native-page (bundle) mapping, derived from src/routes/*.\n` +
    `import type { PageManifest } from 'sparkling-history';\n\n` +
    `export const manifest: PageManifest = ${JSON.stringify({ pages }, null, 2)};\n`;
  writeFileSync(MANIFEST_OUT, manifestBody);

  // 2. Write one entry per page.
  rmSync(ENTRIES_DIR, { recursive: true, force: true });
  const entryList = [];
  for (const p of pages) {
    const dir = join(ENTRIES_DIR, p.id);
    mkdirSync(dir, { recursive: true });
    const entry =
      `// AUTO-GENERATED by scripts/gen-mpa.mjs — do not edit.\n` +
      `// Bundle entry for the '${p.id}' native page. Every page boots the same\n` +
      `// router (from the generated route tree); its start location comes from\n` +
      `// the launch queryItems.\n` +
      `import { mount } from '../../mpa/mount.js';\n\n` +
      `mount();\n`;
    writeFileSync(join(dir, 'index.tsx'), entry);
    entryList.push({ id: p.id, entry: `./src/pages.gen/${p.id}/index.tsx` });
  }

  // 3. Emit an entries manifest the rspeedy config can spread into source.entry.
  const entriesBody =
    `// AUTO-GENERATED by scripts/gen-mpa.mjs — do not edit.\n` +
    `export const pageEntries = ${JSON.stringify(
      Object.fromEntries(entryList.map((e) => [e.id, e.entry])),
      null,
      2,
    )};\n`;
  writeFileSync(join(ROOT, 'src', 'page-entries.gen.ts'), entriesBody);

  console.log(`gen-mpa: ${pages.length} pages ->`, pages.map((p) => `${p.id}[${p.paths.join(',')}]`).join(' '));
}

main();
