// Copyright (c) 2026 TikTok Pte. Ltd.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.
//
// Next-style frontend translator (RFC phase 3 spike).
//
// Reads the Next-style app directory (src/app: layout.tsx, page.tsx, [param]
// segments) and compiles it to the SAME artifacts the TanStack-convention
// frontend produces — proving the runtime is frontend-agnostic:
//
//   1. src/routes-next.gen/       — TanStack route files (bridge modules)
//   2. src/routeTree.next.gen.ts  — via the official @tanstack/router-generator
//   3. src/routes-next.manifest.ts — page manifest (shared lib/page-manifest.mjs)
//   4. src/pages-next.gen/<id>/index.tsx + src/page-entries-next.gen.ts
//
// Authoring markers in app files:
//   export default          — the route component (Next convention)
//   export const container  — native-page boundary (analogue of `page` in the
//                             TanStack convention; same shape, same manifest)
//   export const routeOptions — extra createFileRoute options, spread through
//                             as code (e.g. validateSearch)
import { readdirSync, readFileSync, writeFileSync, mkdirSync, rmSync, existsSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { Generator, getConfig } from '@tanstack/router-generator';
import {
  extractExportedObjectLiteral,
  buildPages,
  renderManifestModule,
} from './lib/page-manifest.mjs';

const ROOT = resolve(process.cwd());
const APP_DIR = join(ROOT, 'src', 'app');
const ROUTES_OUT_DIR = join(ROOT, 'src', 'routes-next.gen');
const TREE_OUT = './src/routeTree.next.gen.ts';
const MANIFEST_OUT = join(ROOT, 'src', 'routes-next.manifest.ts');
const ENTRIES_DIR = join(ROOT, 'src', 'pages-next.gen');

const HEADER = `// AUTO-GENERATED by scripts/gen-next.mjs — do not edit.\n`;

/** Recursively collect page files: [{ segments: ['detail','[id]'], file }] */
function collectPages(dir, segments = []) {
  const out = [];
  for (const name of readdirSync(dir, { withFileTypes: true })) {
    if (name.isDirectory()) {
      out.push(...collectPages(join(dir, name.name), [...segments, name.name]));
    } else if (/^page\.(tsx?|jsx?)$/.test(name.name)) {
      out.push({ segments, file: join(dir, name.name) });
    }
  }
  return out;
}

/** `['detail','[id]']` -> `/detail/$id`; `[]` -> `/` */
function routePathFromSegments(segments) {
  if (segments.length === 0) return '/';
  return (
    '/' +
    segments
      .map((s) => {
        const m = s.match(/^\[(.+)\]$/);
        return m ? `$${m[1]}` : s;
      })
      .join('/')
  );
}

/** `/detail/$id` -> `detail.$id.tsx`; `/` -> `index.tsx` */
function routeFileName(routePath) {
  if (routePath === '/') return 'index.tsx';
  return routePath.slice(1).split('/').join('.') + '.tsx';
}

function main() {
  const pageFiles = collectPages(APP_DIR);
  if (pageFiles.length === 0) throw new Error(`gen-next: no page files under ${APP_DIR}`);

  const routes = pageFiles.map(({ segments, file }) => {
    const src = readFileSync(file, 'utf8');
    return {
      file,
      relImport: ['..', 'app', ...segments, 'page.js'].join('/'),
      path: routePathFromSegments(segments),
      page: extractExportedObjectLiteral(src, 'container', file),
      hasRouteOptions: /export\s+const\s+routeOptions\b/.test(src),
    };
  });

  // 1. Emit bridge route files (TanStack flat convention) into routes-next.gen.
  rmSync(ROUTES_OUT_DIR, { recursive: true, force: true });
  mkdirSync(ROUTES_OUT_DIR, { recursive: true });

  // Root route from app/layout.tsx (plain Outlet root if absent).
  const hasLayout = existsSync(join(APP_DIR, 'layout.tsx'));
  const rootBody = hasLayout
    ? HEADER +
      `import { createRootRoute, Outlet } from '@tanstack/react-router';\n` +
      `import RootLayout from '../app/layout.js';\n\n` +
      `export const Route = createRootRoute({\n` +
      `  component: () => (\n` +
      `    <RootLayout>\n` +
      `      <Outlet />\n` +
      `    </RootLayout>\n` +
      `  ),\n` +
      `});\n`
    : HEADER +
      `import { createRootRoute, Outlet } from '@tanstack/react-router';\n\n` +
      `export const Route = createRootRoute({ component: () => <Outlet /> });\n`;
  writeFileSync(join(ROUTES_OUT_DIR, '__root.tsx'), rootBody);

  for (const r of routes) {
    const imports = r.hasRouteOptions
      ? `import Page, { routeOptions } from '${r.relImport}';\n`
      : `import Page from '${r.relImport}';\n`;
    const pageExport = r.page
      ? `// Page boundary translated from \`export const container\` in the app file.\n` +
        `export const page = ${JSON.stringify(r.page)};\n\n`
      : '';
    const options = r.hasRouteOptions ? `  ...routeOptions,\n  component: Page,\n` : `  component: Page,\n`;
    const body =
      HEADER +
      `import { createFileRoute } from '@tanstack/react-router';\n` +
      imports +
      `\n` +
      pageExport +
      `export const Route = createFileRoute('${r.path}')({\n` +
      options +
      `});\n`;
    writeFileSync(join(ROUTES_OUT_DIR, routeFileName(r.path)), body);
  }

  // 2. Official TanStack generator over the bridge files -> routeTree.next.gen.ts.
  const config = getConfig(
    {
      routesDirectory: './src/routes-next.gen',
      generatedRouteTree: TREE_OUT,
    },
    ROOT,
  );
  const run = async () => {
    await new Generator({ config: await config, root: ROOT }).run();
  };

  // 3. Page manifest via the shared compiler — same artifact as gen-mpa's.
  const pages = buildPages(routes);
  writeFileSync(MANIFEST_OUT, renderManifestModule(pages, 'scripts/gen-next.mjs'));

  // 4. Per-page entries booting the SAME runtime with the next-frontend
  // artifacts (mount is parameterized by routeTree/manifest, no new logic).
  rmSync(ENTRIES_DIR, { recursive: true, force: true });
  const entryList = [];
  for (const p of pages) {
    const dir = join(ENTRIES_DIR, p.id);
    mkdirSync(dir, { recursive: true });
    const entry =
      HEADER +
      `// Bundle entry for the '${p.id}' native page, next-style frontend.\n` +
      `import { mount } from '../../mpa/mount.js';\n` +
      `import { routeTree } from '../../routeTree.next.gen.js';\n` +
      `import { manifest } from '../../routes-next.manifest.js';\n\n` +
      `mount({ pageId: '${p.id}', routeTree, manifest });\n`;
    writeFileSync(join(dir, 'index.tsx'), entry);
    entryList.push({ id: p.id, entry: `./src/pages-next.gen/${p.id}/index.tsx` });
  }
  const entriesBody =
    HEADER +
    `export const nextPageEntries = ${JSON.stringify(
      Object.fromEntries(entryList.map((e) => [e.id, e.entry])),
      null,
      2,
    )};\n`;
  writeFileSync(join(ROOT, 'src', 'page-entries-next.gen.ts'), entriesBody);

  return run().then(() => {
    console.log(
      `gen-next: ${pages.length} pages ->`,
      pages.map((p) => `${p.id}[${p.paths.join(',')}]`).join(' '),
    );
  });
}

await main();
