// Copyright (c) 2026 TikTok Pte. Ltd.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.
//
// MPA codegen — the piece TanStack Router's own generator does not provide.
//
// TanStack's @tanstack/router-generator turns the file convention into a route
// tree (routeTree.gen.ts), assuming one router / one bundle. An MPA needs two
// more artifacts derived from the SAME route files:
//
//   1. src/routes.manifest.ts   — the route -> native-page (bundle) mapping
//   2. src/pages.gen/<id>/index.tsx — one bundle entry per native page
//
// Page boundaries are declared with an `export const page = { id, ... }` in a
// route file (our extension to the convention). Routes without a `page` export
// belong to the root page (the one whose `page` has `root: true`).
// The manifest compilation itself lives in lib/page-manifest.mjs, shared with
// the Next-style frontend (gen-next.mjs) — two authoring conventions, one
// artifact.
import { readdirSync, readFileSync, writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { join, resolve } from 'node:path';
import {
  extractExportedObjectLiteral,
  buildPages,
  renderManifestModule,
} from './lib/page-manifest.mjs';

const ROOT = resolve(process.cwd());
const ROUTES_DIR = join(ROOT, 'src', 'routes');
const MANIFEST_OUT = join(ROOT, 'src', 'routes.manifest.ts');
const ENTRIES_DIR = join(ROOT, 'src', 'pages.gen');

/** Derive a route path from a TanStack file name (fallback if no explicit arg). */
function pathFromFileName(file) {
  let name = file.replace(/\.(tsx?|jsx?)$/, '');
  if (name === 'index') return '/';
  // `detail.$id` -> `/detail/$id`, `a.b` -> `/a/b`
  return '/' + name.split('.').join('/');
}

/** Extract the createFileRoute('...') path argument, if present. */
function extractRoutePath(src, file) {
  const m = src.match(/createFileRoute\(\s*['"]([^'"]+)['"]\s*\)/);
  return m ? m[1] : pathFromFileName(file);
}

function main() {
  const files = readdirSync(ROUTES_DIR).filter(
    (f) => /\.(tsx?|jsx?)$/.test(f) && !f.startsWith('__'),
  );

  const routes = files.map((file) => {
    const src = readFileSync(join(ROUTES_DIR, file), 'utf8');
    return {
      file,
      path: extractRoutePath(src, file),
      page: extractExportedObjectLiteral(src, 'page', file),
    };
  });

  const pages = buildPages(routes);

  // 1. Write the manifest module.
  writeFileSync(MANIFEST_OUT, renderManifestModule(pages, 'scripts/gen-mpa.mjs'));

  // 2. Write one entry per page.
  rmSync(ENTRIES_DIR, { recursive: true, force: true });
  const entryList = [];
  for (const p of pages) {
    const dir = join(ENTRIES_DIR, p.id);
    mkdirSync(dir, { recursive: true });
    const entry =
      `// AUTO-GENERATED by scripts/gen-mpa.mjs — do not edit.\n` +
      `// Bundle entry for the '${p.id}' native page. Every page boots the same\n` +
      `// router (from the generated route tree); its start location comes from\n` +
      `// the launch queryItems, falling back to this page's default route when\n` +
      `// opened by an external deep link.\n` +
      `import { mount } from '../../mpa/mount.js';\n\n` +
      `mount({ pageId: '${p.id}' });\n`;
    writeFileSync(join(dir, 'index.tsx'), entry);
    entryList.push({ id: p.id, entry: `./src/pages.gen/${p.id}/index.tsx` });
  }

  // 3. Emit an entries manifest the rspeedy config can spread into source.entry.
  const entriesBody =
    `// AUTO-GENERATED by scripts/gen-mpa.mjs — do not edit.\n` +
    `export const pageEntries = ${JSON.stringify(
      Object.fromEntries(entryList.map((e) => [e.id, e.entry])),
      null,
      2,
    )};\n`;
  writeFileSync(join(ROOT, 'src', 'page-entries.gen.ts'), entriesBody);

  console.log(`gen-mpa: ${pages.length} pages ->`, pages.map((p) => `${p.id}[${p.paths.join(',')}]`).join(' '));
}

main();
