// Copyright (c) 2026 TikTok Pte. Ltd.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.
//
// MPA codegen — the piece TanStack Router's own generator does not provide.
//
// TanStack's @tanstack/router-generator turns the file convention into a route
// tree (routeTree.gen.ts), assuming one router / one bundle. An MPA needs
// three more artifacts derived from the SAME route files:
//
//   1. src/routes.manifest.ts            — route -> native-page mapping (v1)
//   2. src/pages.gen/<id>/routeTree.ts   — PRUNED route tree per page:
//      own routes carry full options (component, loaders, validateSearch);
//      foreign routes become path-only stubs kept solely so cross-page
//      `navigate({ to, params })` can still build hrefs (which the manifest
//      resolver then dispatches to the host — a stub never renders).
//   3. src/pages.gen/<id>/index.tsx + src/page-entries.gen.ts — entries.
//
// The FULL tree (routeTree.gen.ts) remains the type-level source of truth —
// cross-page links stay type-checked against the whole app. Pruning is a
// build-artifact concern only.
import { writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { collectTanstackRoutes } from './lib/collect-routes.mjs';
import { buildPages, renderManifestModule } from './lib/page-manifest.mjs';

const ROOT = resolve(process.cwd());
const ROUTES_DIR = join(ROOT, 'src', 'routes');
const MANIFEST_OUT = join(ROOT, 'src', 'routes.manifest.ts');
const ENTRIES_DIR = join(ROOT, 'src', 'pages.gen');

const HEADER = `// AUTO-GENERATED by scripts/gen-mpa.mjs — do not edit.\n`;

function identFor(rel) {
  return 'R_' + rel.replace(/\.(tsx?|jsx?)$/, '').replace(/[^a-zA-Z0-9]/g, '_');
}

function renderPrunedTree(page, routes, rootPageId) {
  const own = routes.filter((r) => (r.page?.id ?? rootPageId) === page.id);
  const foreign = routes.filter((r) => (r.page?.id ?? rootPageId) !== page.id);

  const imports = own
    .map((r) => `import { Route as ${identFor(r.file)} } from '../../routes/${r.file.replace(/\.(tsx?|jsx?)$/, '.js')}';`)
    .join('\n');

  const ownDecls = own
    .map(
      (r) =>
        `const ${identFor(r.file)}_route = createRoute({\n` +
        `  ...(${identFor(r.file)} as any).options,\n` +
        `  path: '${r.path}',\n` +
        `  getParentRoute: () => root,\n` +
        `});`,
    )
    .join('\n');

  const stubDecls = foreign
    .map(
      (r, i) =>
        `// '${r.path}' lives in page '${r.page?.id ?? rootPageId}' — path-only stub.\n` +
        `const stub_${i} = createRoute({ path: '${r.path}', getParentRoute: () => root });`,
    )
    .join('\n');

  const children = [
    ...own.map((r) => `${identFor(r.file)}_route`),
    ...foreign.map((_, i) => `stub_${i}`),
  ].join(', ');

  return (
    HEADER +
    `// Pruned route tree for the '${page.id}' page: only this page's routes\n` +
    `// carry components/options; every other route is a path-only stub for\n` +
    `// href building. The full tree (routeTree.gen.ts) stays the type-level\n` +
    `// source of truth.\n` +
    `/* eslint-disable @typescript-eslint/no-explicit-any */\n` +
    `import { createRootRoute, createRoute } from '@tanstack/react-router';\n` +
    `import { Route as rootRouteImport } from '../../routes/__root.js';\n` +
    (imports ? imports + '\n' : '') +
    `\n` +
    `// Fresh root cloned from the app root's options: pruned trees must not\n` +
    `// mutate shared file-route singletons (the full tree links them too).\n` +
    `const root = createRootRoute((rootRouteImport as any).options);\n\n` +
    (ownDecls ? ownDecls + '\n' : '') +
    (stubDecls ? stubDecls + '\n' : '') +
    `\nexport const routeTree = root.addChildren([${children}]);\n`
  );
}

function main() {
  const routes = collectTanstackRoutes(ROUTES_DIR);
  const pages = buildPages(routes);
  const rootPageId = routes.find((r) => r.page?.root)?.page.id;

  // 1. Manifest module (schema v1).
  writeFileSync(MANIFEST_OUT, renderManifestModule(pages, 'scripts/gen-mpa.mjs'));

  // 2. Per-page pruned tree + entry.
  rmSync(ENTRIES_DIR, { recursive: true, force: true });
  const entryList = [];
  for (const p of pages) {
    const dir = join(ENTRIES_DIR, p.id);
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, 'routeTree.ts'), renderPrunedTree(p, routes, rootPageId));
    const entry =
      HEADER +
      `// Bundle entry for the '${p.id}' native page. Boots the shared runtime\n` +
      `// with this page's pruned tree; start location comes from the launch\n` +
      `// queryItems, falling back to this page's default route on deep link.\n` +
      `import { mount } from '../../mpa/mount.js';\n` +
      `import { routeTree } from './routeTree.js';\n` +
      `import { manifest } from '../../routes.manifest.js';\n\n` +
      `mount({ pageId: '${p.id}', routeTree, manifest });\n`;
    writeFileSync(join(dir, 'index.tsx'), entry);
    entryList.push({ id: p.id, entry: `./src/pages.gen/${p.id}/index.tsx` });
  }

  // 3. Entries manifest for the rspeedy config.
  const entriesBody =
    HEADER +
    `export const pageEntries = ${JSON.stringify(
      Object.fromEntries(entryList.map((e) => [e.id, e.entry])),
      null,
      2,
    )};\n`;
  writeFileSync(join(ROOT, 'src', 'page-entries.gen.ts'), entriesBody);

  console.log(
    `gen-mpa: ${pages.length} pages (pruned trees) ->`,
    pages.map((p) => `${p.id}[${p.paths.join(',')}]`).join(' '),
  );
}

main();
