// Copyright 2026 The Sparkling Authors. All rights reserved.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.

import { createHash } from 'node:crypto';
import {
    mkdir,
    rm,
    writeFile,
} from 'node:fs/promises';
import {
    dirname,
    join,
    relative,
    sep,
} from 'node:path';
import {
    Generator,
    getConfig,
} from '@tanstack/router-generator';
import type {
    VirtualRootRoute,
    VirtualRouteNode,
} from '@tanstack/virtual-file-routes';
import { scanSparklingRoutes } from './scanner';
import type {
    GeneratedSparklingRoutes,
    ScannedContainer,
    SparklingRouterPluginOptions,
} from './types';

interface RouteTreeNode {
    segment: string;
    file?: string;
    indexFile?: string;
    layoutFile?: string;
    children: Map<string, RouteTreeNode>;
}

function portable(path: string): string {
    return path.split(sep).join('/');
}

function createNode(segment: string): RouteTreeNode {
    return { segment, children: new Map() };
}

function insertRoute(
    root: RouteTreeNode,
    segments: string[],
): RouteTreeNode {
    let current = root;
    segments.forEach((segment) => {
        let child = current.children.get(segment);
        if (!child) {
            child = createNode(segment);
            current.children.set(segment, child);
        }
        current = child;
    });
    return current;
}

function buildVirtualChildren(
    node: RouteTreeNode,
    parentId: string,
): VirtualRouteNode[] {
    const children = [...node.children.values()]
        .sort((left, right) => left.segment.localeCompare(right.segment))
        .map((child) => buildVirtualRoute(child, parentId));
    if (node.indexFile) {
        children.unshift({ type: 'index', file: node.indexFile });
    }
    if (node.layoutFile) {
        return [{
            type: 'layout',
            id: `${parentId || 'root'}-layout`,
            file: node.layoutFile,
            children,
        }];
    }
    return children;
}

function buildVirtualRoute(
    node: RouteTreeNode,
    parentId: string,
): VirtualRouteNode {
    const id = `${parentId}/${node.segment}`;
    const children = buildVirtualChildren(node, id);
    return {
        type: 'route',
        path: node.segment,
        file: node.file,
        children: children.length > 0 ? children : undefined,
    };
}

function virtualConfig(
    container: ScannedContainer,
    rootRouteFile: string,
): VirtualRootRoute {
    const root = createNode('');
    container.routes.forEach((route) => {
        const node = insertRoute(root, route.routeSegments);
        if (route.kind === 'index') {
            node.indexFile = route.relativePath;
        } else if (route.kind === 'layout') {
            node.layoutFile = route.relativePath;
        } else {
            node.file = route.relativePath;
        }
    });

    return {
        type: 'root',
        file: rootRouteFile,
        children: buildVirtualChildren(root, ''),
    };
}

function entryName(bundle: string): string {
    return bundle.replace(/\.lynx\.bundle$/, '');
}

function routeTreeImport(fromDirectory: string, routeTreePath: string): string {
    let path = portable(relative(fromDirectory, routeTreePath))
        .replace(/\.(?:ts|tsx)$/, '.js');
    if (!path.startsWith('.')) {
        path = `./${path}`;
    }
    return path;
}

function entrySource(
    routeTreePath: string,
    manifestPath: string,
    entryPath: string,
    bundle: string,
): string {
    const directory = dirname(entryPath);
    const routeTree = routeTreeImport(directory, routeTreePath);
    const manifest = routeTreeImport(directory, manifestPath).replace(/\.json\.js$/, '.json');
    return `// Generated by sparkling-router-plugin. Do not edit.
import 'url-search-params-polyfill'
import { root } from '@lynx-js/react'
import { RouterProvider } from '@tanstack/react-router'
import { createSparklingRouter, type RouteManifest } from 'sparkling-router'
import manifestJSON from '${manifest}'
import { routeTree } from '${routeTree}'

const runtime = createSparklingRouter({
  routeTree,
  manifest: manifestJSON as RouteManifest,
  containerBundle: '${bundle}',
})

root.render(<RouterProvider router={runtime.router} />)

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  import.meta.webpackHot.dispose(() => runtime.destroy())
}
`;
}

function manifestVersion(
    manifest: Omit<GeneratedSparklingRoutes['manifest'], 'version'>,
): string {
    return createHash('sha256')
        .update(JSON.stringify(manifest))
        .digest('hex')
        .slice(0, 12);
}

export async function generateSparklingRoutes(
    root: string,
    options: SparklingRouterPluginOptions = {},
): Promise<GeneratedSparklingRoutes> {
    const routesDirectory = join(root, options.routesDirectory ?? 'src/routes');
    const generatedDirectory = join(
        root,
        options.generatedDirectory ?? 'src/.sparkling-router',
    );
    const scanned = await scanSparklingRoutes(routesDirectory);
    await rm(generatedDirectory, { recursive: true, force: true });
    await mkdir(generatedDirectory, { recursive: true });

    const manifestWithoutVersion = {
        scheme: { base: options.schemeBase ?? 'hybrid://lynxview_page' },
        containers: scanned.containers.map((container) => ({
            bundle: container.bundle,
            presentation: container.presentation,
            routes: [...new Set(
                container.routes
                    .filter((route) => route.kind !== 'layout')
                    .map((route) => route.routePath),
            )].sort().map((path) => ({ path })),
            ...(container.containerOptions
                ? { containerOptions: container.containerOptions }
                : {}),
        })),
    };
    const manifest = {
        version: options.manifestVersion ?? manifestVersion(manifestWithoutVersion),
        ...manifestWithoutVersion,
    };
    const manifestPath = join(generatedDirectory, 'manifest.json');
    await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);

    const entries: Record<string, string> = {};
    for (const container of scanned.containers) {
        const outputDirectory = join(generatedDirectory, entryName(container.bundle));
        const routeTreePath = join(outputDirectory, 'routeTree.gen.ts');
        const entryPath = join(outputDirectory, 'entry.tsx');
        await mkdir(outputDirectory, { recursive: true });

        const config = getConfig({
            target: 'react',
            routesDirectory,
            generatedRouteTree: routeTreePath,
            virtualRouteConfig: virtualConfig(container, scanned.rootRouteFile),
            disableLogging: options.disableLogging ?? true,
            enableRouteTreeFormatting: false,
        }, root);
        await new Generator({ config, root }).run();
        await writeFile(
            entryPath,
            entrySource(routeTreePath, manifestPath, entryPath, container.bundle),
        );
        entries[entryName(container.bundle)] = entryPath;
    }

    return { entries, manifestPath, manifest };
}
