// Copyright (c) 2026 TikTok Pte. Ltd.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.

import fs from 'node:fs'
import path from 'node:path'
import type { RouteManifest } from 'sparkling-router'
import { scanRouteContainers } from './scan.js'
import type { PluginOptions, ScanResult } from './types.js'

export interface GenerateResult {
  scan: ScanResult
  manifest: RouteManifest
  manifestPath: string
  entries: Record<string, string>
  entriesPath?: string
  containerDirs: string[]
}

const DEFAULTS = {
  routesDirectory: 'src/routes',
  manifestOutput: 'src/route-manifest.gen.json',
  containersOutput: 'src/generated/containers',
  schemeBase: 'hybrid://lynxview_page',
  manifestVersion: '1',
  emitEntries: true,
}

/**
 * Scan routes, emit:
 * - global `route-manifest.gen.json`
 * - per-container entry stubs under `generated/containers/<id>/`
 * - optional `rspeedy-entries.gen.json` for `source.entry` injection
 */
export function generateSparklingRoutes(
  projectRoot: string,
  options: PluginOptions = {},
): GenerateResult {
  const opts = { ...DEFAULTS, ...options }
  const routesDir = path.resolve(projectRoot, opts.routesDirectory)
  const scan = scanRouteContainers(routesDir)

  const manifest: RouteManifest = {
    version: opts.manifestVersion,
    scheme: { base: opts.schemeBase },
    containers: scan.containers.map((c) => ({
      bundle: `${c.id}.lynx.bundle`,
      presentation: c.presentation,
      routes: c.routes.length > 0 ? c.routes : [{ path: `/${c.id.replace(/\./g, '/')}` }],
      containerOptions: c.containerOptions,
    })),
  }

  const manifestPath = path.resolve(projectRoot, opts.manifestOutput)
  fs.mkdirSync(path.dirname(manifestPath), { recursive: true })
  fs.writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, 'utf8')

  const containersRoot = path.resolve(projectRoot, opts.containersOutput)
  fs.mkdirSync(containersRoot, { recursive: true })

  const entries: Record<string, string> = {}
  const containerDirs: string[] = []

  for (const container of scan.containers) {
    const dir = path.join(containersRoot, container.id)
    fs.mkdirSync(dir, { recursive: true })
    containerDirs.push(dir)

    const entryFile = path.join(dir, 'index.tsx')
    const routesLiteral = JSON.stringify(container.routes.map((r) => r.path), null, 2)
    const contents = `/* eslint-disable */
// auto-generated by sparkling-router-plugin — do not edit
import 'url-search-params-polyfill'
import { root } from '@lynx-js/react'

export const CONTAINER_ID = ${JSON.stringify(container.id)}
export const OWNED_ROUTES = ${routesLiteral} as const
export const PRESENTATION = ${JSON.stringify(container.presentation)} as const

// Host apps should replace this stub with createSparklingHistory + RouterProvider.
root.render(
  <view>
    <text>Container ${container.id}</text>
  </view>,
)
`

    fs.writeFileSync(entryFile, contents, 'utf8')
    entries[container.id] = path.relative(projectRoot, entryFile).replace(/\\/g, '/')
  }

  let entriesPath: string | undefined
  if (opts.emitEntries) {
    entriesPath = path.resolve(projectRoot, path.dirname(opts.manifestOutput), 'rspeedy-entries.gen.json')
    fs.writeFileSync(entriesPath, `${JSON.stringify(entries, null, 2)}\n`, 'utf8')
  }

  return { scan, manifest, manifestPath, entries, entriesPath, containerDirs }
}
