// AUTO-GENERATED by scripts/gen-mpa.mjs — do not edit.
// Bundle entry for the 'settings' native page. Every page boots the same
// router (from the generated route tree); its start location comes from
// the launch queryItems.
import { mount } from '../../mpa/mount.js';

mount();
