// AUTO-GENERATED by scripts/gen-mpa.mjs — do not edit.
// Pruned route tree for the 'settings' page: only this page's routes
// carry components/options; every other route is a path-only stub for
// href building. The full tree (routeTree.gen.ts) stays the type-level
// source of truth.
/* eslint-disable @typescript-eslint/no-explicit-any */
import { createRootRoute, createRoute } from '@tanstack/react-router';
import { Route as rootRouteImport } from '../../routes/__root.js';
import { Route as R_settings } from '../../routes/settings.js';

// Fresh root cloned from the app root's options: pruned trees must not
// mutate shared file-route singletons (the full tree links them too).
const root = createRootRoute((rootRouteImport as any).options);

const R_settings_route = createRoute({
  ...(R_settings as any).options,
  path: '/settings',
  getParentRoute: () => root,
});
// '/' lives in page 'home' — path-only stub.
const stub_0 = createRoute({ path: '/', getParentRoute: () => root });
// '/detail/$id' lives in page 'detail' — path-only stub.
const stub_1 = createRoute({ path: '/detail/$id', getParentRoute: () => root });
// '/profile' lives in page 'home' — path-only stub.
const stub_2 = createRoute({ path: '/profile', getParentRoute: () => root });

export const routeTree = root.addChildren([R_settings_route, stub_0, stub_1, stub_2]);
