// AUTO-GENERATED by scripts/gen-mpa.mjs — do not edit.
// Bundle entry for the 'detail' native page. Every page boots the same
// router (from the generated route tree); its start location comes from
// the launch queryItems, falling back to this page's default route when
// opened by an external deep link.
import { mount } from '../../mpa/mount.js';

mount({ pageId: 'detail' });
