// AUTO-GENERATED by scripts/gen-mpa.mjs — do not edit.
// Bundle entry for the 'detail' native page. Boots the shared runtime
// with this page's pruned tree; start location comes from the launch
// queryItems, falling back to this page's default route on deep link.
import { mount } from '../../mpa/mount.js';
import { routeTree } from './routeTree.js';
import { manifest } from '../../routes.manifest.js';

mount({ pageId: 'detail', routeTree, manifest });
