// Copyright (c) 2026 TikTok Pte. Ltd.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.

/**
 * Build-time route-manifest generation (Node-only).
 *
 * Sparkling pages live in different JS heaps, so the route table connecting
 * them must be established AHEAD of time and embedded into every bundle.
 * This module derives that table from the file-based page convention:
 *
 *   src/pages/<name>/index.*        →  page bundle "<name>"
 *   src/pages/<name>/routes.json    →  routes owned by the page (optional)
 *
 * Without `routes.json`, a page owns a single conventional route:
 * `/` for root pages (`main`/`index`/`home` by default), `/<name>` otherwise.
 *
 * `routes.json` shape (all fields optional except `routes`):
 * ```json
 * {
 *   "routes": ["/detail/:id", { "path": "/detail/:id/edit", "name": "edit" }],
 *   "default": "/detail/1",
 *   "params": { "hide_nav_bar": true }
 * }
 * ```
 */

import fs from 'node:fs'
import path from 'node:path'
import type {
  RouteManifest,
  RouteManifestPage,
  RouteManifestRoute,
} from '../manifest'

export interface ScanPagesOptions {
  /** Directory containing one sub-directory per page (e.g. `src/pages`). */
  pagesDir: string
  /** Base scheme recorded in the manifest. */
  scheme?: string
  /** Per-page route config file name. Default `routes.json`. */
  configFile?: string
  /** Page names whose conventional route is `/`. Default main/index/home. */
  rootPages?: string[]
}

interface PageRoutesConfig {
  routes?: RouteManifestRoute[]
  default?: string
  params?: Record<string, string | number | boolean>
}

export function scanPages(options: ScanPagesOptions): RouteManifest {
  const configFile = options.configFile ?? 'routes.json'
  const rootPages = options.rootPages ?? ['main', 'index', 'home']

  if (!fs.existsSync(options.pagesDir)) {
    throw new Error(
      `[sparkling-history] pagesDir does not exist: ${options.pagesDir}`
    )
  }

  const pages: RouteManifestPage[] = []
  const entries = fs
    .readdirSync(options.pagesDir, { withFileTypes: true })
    .filter(entry => entry.isDirectory())
    .sort((a, b) => a.name.localeCompare(b.name))

  for (const entry of entries) {
    const pageDir = path.join(options.pagesDir, entry.name)
    const configPath = path.join(pageDir, configFile)

    let config: PageRoutesConfig = {}
    if (fs.existsSync(configPath)) {
      const raw = JSON.parse(fs.readFileSync(configPath, 'utf8')) as
        | PageRoutesConfig
        | RouteManifestRoute[]
      config = Array.isArray(raw) ? { routes: raw } : raw
    }

    const conventionalRoute = rootPages.includes(entry.name)
      ? '/'
      : `/${entry.name}`

    pages.push({
      bundle: entry.name,
      routes: config.routes?.length ? config.routes : [conventionalRoute],
      ...(config.default ? { default: config.default } : {}),
      ...(config.params ? { params: config.params } : {}),
    })
  }

  return {
    ...(options.scheme ? { scheme: options.scheme } : {}),
    pages,
  }
}

/** Render a manifest as an importable TypeScript module. */
export function renderManifestModule(manifest: RouteManifest): string {
  return [
    '// AUTO-GENERATED by sparkling-history/codegen — DO NOT EDIT.',
    "import { defineRouteManifest } from 'sparkling-history'",
    '',
    `export default defineRouteManifest(${JSON.stringify(manifest, null, 2)})`,
    '',
  ].join('\n')
}

export interface GenerateRouteManifestOptions extends ScanPagesOptions {
  /** Path of the generated module (e.g. `src/generated/route-manifest.ts`). */
  outFile: string
}

/**
 * Scan pages and write the manifest module. Skips the write when content is
 * unchanged so watch-mode builds don't loop.
 */
export function generateRouteManifest(
  options: GenerateRouteManifestOptions
): RouteManifest {
  const manifest = scanPages(options)
  const content = renderManifestModule(manifest)
  const current = fs.existsSync(options.outFile)
    ? fs.readFileSync(options.outFile, 'utf8')
    : null
  if (current !== content) {
    fs.mkdirSync(path.dirname(options.outFile), { recursive: true })
    fs.writeFileSync(options.outFile, content)
  }
  return manifest
}

/**
 * Minimal rsbuild/rspeedy plugin: regenerates the manifest before builds and
 * dev-server startup, so `src/pages/**` stays the single source of truth.
 */
export function pluginRouteManifest(options: GenerateRouteManifestOptions): {
  name: string
  setup(api: {
    onBeforeBuild?: (fn: () => void) => void
    onBeforeStartDevServer?: (fn: () => void) => void
  }): void
} {
  return {
    name: 'sparkling-history:route-manifest',
    setup(api) {
      const regenerate = () => {
        generateRouteManifest(options)
      }
      regenerate()
      api.onBeforeBuild?.(regenerate)
      api.onBeforeStartDevServer?.(regenerate)
    },
  }
}
